name: CI Pipeline
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/workflows/*"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm Package Manager
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Get pnpm Store Directory
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm run lint
      - name: Build/Bundle Application
        if: github.event_name != 'pull_request'
        run: pnpm run build
      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: 'dist'
          path: 'dist'
  
  deploy:
    needs: setup_and_build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: 'dist'
          path: 'dist'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        id: deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

